core: Document how to circumvent the django.contrib.auth.views missing error.
This error:

    ======================================================================
    ERROR: test_current_site_in_context_after_login (django.contrib.auth.tests.views.LoginTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/walter/.virtualenvs/bosso/local/lib/python2.7/site-packages/django/contrib/auth/tests/views.py", line 294, in test_current_site_in_context_after_login
        response = self.client.get(reverse('django.contrib.auth.views.login'))
      File "/home/walter/.virtualenvs/bosso/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 512, in reverse
        return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
      File "/home/walter/.virtualenvs/bosso/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 432, in _reverse_with_prefix
        "arguments '%s' not found." % (lookup_view_s, args, kwargs))
    NoReverseMatch: Reverse for 'django.contrib.auth.views.login' with arguments '()' and keyword arguments '{}' not found.

Is triggered by something like this:

    class YubikeyVerificationMiddleWare(object):
        def __init__(self):
            try:
                register_yubikey_url = reverse('register_yubikey')
    ...

And it is avoided by one of the two techniques mentioned in the commit.